### ISSUE TITLE
CUBLAS Error on 2x3090 

### ISSUE THREAD

**Issue by mperacchi** [facebookresearch/llama#59]
I'm having problems with CUBLAS while running the example code. I've tried to update the gpu driver but it didn't fix the issue.

My machine has:
**OS**: Ubuntu 20.04
**Driver**: 515
**Env**: python3.8, pip (not using conda), fresh virtualenv,  installed requirements from the repo
**Cuda**: 11.7 (downloaded directly from torch)
**GPU**: 2 x 3090 (24GB x 2)

torchrun --nproc_per_node 1 example.py --ckpt_dir weights/7B --tokenizer_path weights/tokenizer.model

> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Loaded in 6.55 seconds
Traceback (most recent call last):
  File "example.py", line 72, in <module>
    fire.Fire(main)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example.py", line 64, in main
    results = generator.generate(prompts, max_gen_len=256, temperature=temperature, top_p=top_p)
  File "/home/uname/Documents/llama/llama/generation.py", line 42, in generate
    logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/uname/Documents/llama/llama/model.py", line 235, in forward
    h = layer(h, start_pos, freqs_cis, mask)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/uname/Documents/llama/llama/model.py", line 193, in forward
    h = x + self.attention.forward(self.attention_norm(x), start_pos, freqs_cis, mask)
  File "/home/uname/Documents/llama/llama/model.py", line 121, in forward
    xq, xk, xv = self.wq(x), self.wk(x), self.wv(x)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/fairscale/nn/model_parallel/layers.py", line 290, in forward
    output_parallel = F.linear(input_parallel, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8480) of binary: /home/uname/Documents/llama/venv/bin/python
Traceback (most recent call last):
  File "/home/uname/Documents/llama/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/uname/Documents/llama/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-02_15:13:08
  host      : uname-ares2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8480)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zoanthal** [comment]
Use python 3.10 environment

**Comment by mperacchi** [comment]
> Use python 3.10 environment

I tried, nothing changes

**Comment by mperacchi** [comment]
My CUDA installation was broken, I tried to create a new docker with CUDA inside and it worked

**Comment by taehong-moon** [comment]
@mperacchi I have same problem. Could you share the details of CUDA and conda env?
