### ISSUE TITLE
Cant use Windows as fire packacge requires NCCL

### ISSUE THREAD

**Issue by marcusobrien** [facebookresearch/llama#699]
Hi, 

How can I use this system on Windows when it can only be run with NCCL ? 

The instructions require a lot of changing for this - the example script can not be without switching the backend to goo from NCCL

RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23152) of binary: U:\Miniconda3\envs\llama2env\python.exe

Then you can't use the torchrun.exe as the example shows, as this fails/complains due to unable to **start a process**, you have to use python -m  torchrun-script

As the above python script will actually run.

Has anyone tried these instructions with Windows 10 Pro , using CUDA, and a NVidia GPU ?

**Comment by slalla** [comment]
I am also having this issues. It seems that #697 is also related.

**Comment by AlmogAmiga** [comment]
Thanks @robertofuentesr it solved my problem! :D

**Comment by Grunthos** [comment]
When I select 'gloo' as the backend, it does not use the GPU -- it seems to default to the CPU. Is there a solution to this?

**Comment by divonelnc** [comment]
> Hi, I am not expert. But I read a little this: https://pytorch.org/docs/stable/distributed.html (in summary nccl not working on windows better use gloo) and I added this to the code (in the beginning) and it works in windows 11: Fix:
> 
> ```
> import os 
> import torch
> os.environ['PL_TORCH_DISTRIBUTED_BACKEND'] = 'gloo'
> os.environ['NCCL_DEBUG'] = 'INFO'
> torch.distributed.init_process_group(backend="gloo")
> ```
> 
> this is my output:
> 
> running this: **torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir "llama-2-7b/" --tokenizer_path "tokenizer.model" --max_seq_len 128 --max_batch_size 4**
> 
> C:\Users\Rober\Desktop\llama 2\llama>torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir "llama-2-7b/" --tokenizer_path "tokenizer.model" --max_seq_len 128 --max_batch_size 4 NOTE: Redirects are currently not supported in Windows or MacOs. [W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Rober]:29500 (system error: 10049 - unknown error). [W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Rober]:29500 (system error: 10049 - unknown error). [W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Rober]:29500 (system error: 10049 - unknown error). [W C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Rober]:29500 (system error: 10049 - unknown error).
> 
> > initializing model parallel with size 1
> > initializing ddp with size 1
> > initializing pipeline with size 1
> > Loaded in 35.25 seconds
> > I believe the meaning of life is
> > to be happy. I believe we are all born with the potential to be happy. The meaning of life is to be happy, but the way to get there is not always easy.
> > The meaning of life is to be happy. It is not always easy to be happy, but it is possible. I believe that
> 
> ==================================
> 
> Simply put, the theory of relativity states that
> 
> > 1. time, space, and mass are relative, and 2) the speed of light is constant, regardless of the observer’s velocity.
> >    The theory of relativity was first proposed by Albert Einstein in 1905. The theory was later modified and expanded by Einstein in 19
> 
> ==================================
> 
> A brief message congratulating the team on the launch:
> 
> ```
>     Hi everyone,
> 
>     I just
> ```
> 
> > wanted to say a big congratulations to the team on the launch of the new website.
> 
> ```
>     I think it looks fantastic and I'm sure it'll be a huge success.
> 
>     Please let me know if you need anything else from me.
> 
>     Best,
> ```
> 
> ==================================
> 
> Translate English to French:
> 
> ```
>     sea otter => loutre de mer
>     peppermint => menthe poivrée
>     plush girafe => girafe peluche
>     cheese =>
> ```
> 
> > fromage
> > maple syrup => sirop d'érable
> > honey => miel
> > pineapple => ananas
> > apple => pomme
> > pine tree => pin
> > oak tree => chêne
> > birch => bouleau
> > cherry
> 
> ==================================
> 
> If someone wants to add something more I would be happy I do not comprehend completely the mistake.

I just tried this with Llama 3... I tried to put it at the top of the example_***_completion.py files or at the top of llama/generation.py file, but no success. It still complains about NCCL not being built in. :(
